.PHONY: help
.DEFAULT_GOAL := help

locale: locale_jsons locale_keys

locale_keys: 
	dart scripts/localization_keys.dart -s assets/translations/en-US.json -o lib/services/i18n/locale_key.g.dart

locale_jsons: 
	dart scripts/localization_jsons.dart -s assets/translations/source.csv -o assets/translations

# autogenerated help
help:										## print help
#		"\033[36m" - set output to blue color
# 		"\033[0m" - set output to white color
	@echo
	@echo available commands:
	@echo
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\t make \033[36m%-30s\033[0m %s\n", $$1, $$2}'
	@echo
	