name: memoroutines
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  path_provider: ^2.0.15
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  go_router: ^7.0.3
  provider: ^6.0.5
  logger: ^1.4.0
  flutter_hooks: ^0.18.6
  share_plus: ^7.0.2
  flex_color_scheme: ^7.1.2
  flutter_native_splash: ^2.3.1
  easy_localization: ^3.0.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  styled_widget: ^0.4.1
  visibility_detector: ^0.3.3
  bottom_sheet: ^3.1.2
  package_info_plus: ^4.0.2
  line_icons: ^2.0.1
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  args: ^2.4.2
  csv: ^5.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
